name: destroy_tf_stack

on: workflow_dispatch

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  destroy-terraform:
    name: "Destroy TF Stack"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdktf
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get run id of the latest successful build workflow
        id: get_run_id
        run: |
          echo "${{ github.repository }}"
          echo "${{ secrets.GITHUB_TOKEN }}"
          run_id=$(curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/build_and_deploy/runs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Accept: application/vnd.github.v3+json' \
            | jq -r '.workflow_runs[] | select(.conclusion=="success") | .id' | head -n 1)
          echo "run_id=$run_id" >> $GITHUB_ENV

      - run: echo "$run_id"

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: lambda-out
          gitub-token: ${{ secrets.GITHUB_TOKEN }}
          path: cdktf/lambda-out
          run-id: ${{env.run_id}}

      - name: Install dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: terraform destroy cognito
        run: npx cdktf-cli destroy cognito-lambda --auto-approve
