name: Build Lambda Application

on:
  push:
    branches:
      - main
      - develop
      - "feat/**"
      - "fix/**"
      - "release/**"
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

defaults:
  run:
    working-directory: lambda-auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
