name: Build Lambda Application

on:
  push:
    branches:
      - main
      - develop
      - "feat/**"
      - "fix/**"
      - "release/**"
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda-auth
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

  deploy-terraform:
    runs-on: ubuntu-latest
    environment:
      name: approvers
    needs: [build-lambda]
    defaults:
      run:
        working-directory: ./cdktf
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Deploy
        run: cdktf deploy --auto-approve '*' # Deploys all stacks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  destroy-terraform:
    runs-on: ubuntu-latest
    needs: [deploy-terraform]
    defaults:
      run:
        working-directory: cdktf
    environment:
      name: approvers
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli@next

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Install dependencies
        run: npm ci

      - name: Generate bindings for providers and modules
        run: cdktf get

      - name: Destroy
        run: cdktf destroy --auto-approve '*' # Destroys all stacks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
