name: Build Lambda Application

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda-auth
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

  deploy-terraform:
    runs-on: ubuntu-latest
    environment:
      name: approvers
    needs: [build-lambda]
    defaults:
      run:
        working-directory: cdktf
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: show folder
        run: pwd

      - name: terraform-cdk-action
        uses: hashicorp/terraform-cdk-action@v3.0.7
        with:
          cdktfVersion: 0.20.4
          terraformVersion: 1.7.4
          mode: plan-only
          stackName: cognito-lambda
          githubToken: ${{ secrets.GITHUB_TOKEN }}
